sudo: false
language: php
dist: trusty
matrix:
  fast_finish: true
  include:
  - php: '5.4'
  - php: '5.5'
  - php: '5.6'
  - php: '7.0'
  - php: '7.1'
    env:
    - DEPLOY=1
    - SNIFF=1
before_script:
- export PHPCS_DIR=/tmp/phpcs
- export SNIFFS_DIR=/tmp/sniffs
- if [[ "$SNIFF" == "1" ]]; then git clone -b 2.9 --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git
  $PHPCS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b master --depth 1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then git clone -b 7.1.4 --depth 1 https://github.com/wimg/PHPCompatibility.git
  $SNIFFS_DIR/PHPCompatibility; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs --config-set installed_paths
  $SNIFFS_DIR; fi
- if [[ "$SNIFF" == "1" ]]; then phpenv rehash; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jscs; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g jshint; fi
- if [[ "$SNIFF" == "1" ]]; then wget https://develop.svn.wordpress.org/trunk/.jshintrc;fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g grunt-cli;fi
- if [[ "$SNIFF" == "1" ]]; then npm install; fi
- if [[ "$SNIFF" == "1" ]]; then npm install -g grunt-checktextdomain;fi
script:
- mkdir -p build/logs
- find -L . -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l
- if [[ "$SNIFF" == "1" ]]; then jshint ./assets/js/*.js; fi
- if [[ "$SNIFF" == "1" ]]; then jscs ./assets/js/*.js; fi
- if [[ "$SNIFF" == "1" ]]; then grunt textdomain; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./*.php --standard=./phpcs.ruleset.xml
  --extensions=php; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/*.php --standard=./phpcs.ruleset.xml
  --extensions=php --ignore=./inc/plugin-activation.php,./node_modules/*.php; fi
- if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n ./**/**/*.php
  --standard=./phpcs.ruleset.xml --extensions=php --ignore=./node_modules/**/*.php;fi
notifications:
  email: false
  slack:
    secure: WFuEWy1NIVLAfo81aAdYkGaZYciHTR6ySzjH69xfaZuQYciT6LJXCrPj+aOP8EtnpixrmbW64ChoQYfth9a0m3LUF5wy2gsbdBQr5gIMr/tpxLAZ53E2wBVWnHF79VQUNiqfrInPe3bFYGkORGyqNBxB9Rq8G6IaY2mXL1BXn7sBZQaxZBGjgNMvfMnVtZrdllFcl0rEDUgyXKvjalM5s+Evg6ghUavN42SpB421GEvXs/WX4CAXJAiRpBYxrtdOuDd4aWTj0NzF6ltEUMTWnke36YfCP2QKi4ghQYx6QHiL4Psv22nIJJlKHoYJRt6GfMtsu8BNXxmuOoHOXxPXXEAEWFJHYYCmhVXxc0fb4LA+QUt89Ica17jUK8jsCQw05GwN2e72PFYaOAaJp2w1szUX4Y25z3N57UGpx9qkg2i8pNYHGZ9mHlw1dHCRTVPlVdSCwFKGl2ZVEsO336EUjxJ46bcFxN2wwOA9rNlygJBI8xJbca+muL/MiOOyGWFwwjS0BlK062AFIFAGZXDyaciT3jcZ1XPZ773sdBfdn474az35phf44sWnluOopefvkyWvyoXFOCZf5INiOsrnYrMmaztymngrzOuyw3OEt8sumTCeT7wgu34tSKaYVz2JGb+SU87WfzaNLsReMxVOvYb13ktEeE8jvtVqKh17Gtc=
cache:
  directories:
  - node_modules
after_success:
- wget https://raw.githubusercontent.com/cristianraiber/travis-deployment/master/deploy.sh
- bash deploy.sh
- grunt build-archive
- sh set_tags.sh
env:
  global:
  - SVN_REPO: https://plugins.svn.wordpress.org/simple-author-box/
  - secure: klXpvMBGX7JwMo9Q+EpnITS5B+xdmehyl0M7slHZE3tlM8zsjbhFb7kKyXPQcGRpOg3+PKesnH3m6RF8vsb/ga88iFT6Qy+LR7ZFee/NBp4HmmLDF3r5B9MN5hpEhuLVLvDCuvEoDbZvPz8itTgKXiLTNs0YRR0dBfW73Jwe4FpJZ5PK1oVCqD/+3AsU8tM3uKJwt86nowhLu7KUpGXnIJUvpKb8w8RW6w1hMreP0KQpl91cgLIVgm9QUXTgX1TrdVb17DOYRr0Rau6vFSYc/1xS2x2Q03jVJ8JtUndkW4H80+j4SlKuRih7jZo/luDbS2azhLPbUyCTKWHgp7dy+cc2WpW3JxVard+zJ9y8q99/WVdjA0KW2GmfmNSTH9JzyRyp7K5oD39aYSavwNC2jEBPLQ1gKzEBcHWQfSGwOq5LV2i1XuNlIMFci1CkPIWPoFE62QIBkKSkJxnDT1D5E72EF8qIe0IUN0JrrpdHmdTAwrTS5ctFVoHu4grfNLjEl3xc2z10JH5wKtbIuImgSz6JargO0BE6N6FcqllFD9hmHEyL80GWcCNm1eMyR/JXhljo22nZ4KTbJ2qSnBIiChpYcgY82U75IVtLtGAU7ff31LsbQk4VPqOssbPefIt6yGhxj0pduU47Jqf8QO0yIyWJ1yNKwJu/DPd3vOnSMFg=
  - secure: lpJeItlawR0IdHzK9RBnbZCEvhtKD/VvCqcOmc8tHByuCqnJqml8f3TF/ledLdHGWoL71eZP/ofHgGiAbX2zUNKKxGqfy5YYWFge/+kMYA8YSpBFO0OxzZb95BnIt5IMBDCINIcXL4CSR5x+QYuvimXEJ3dhJJvdch8jSVHkNNu6QsoXhRq/2LB/yHlZN+KSXatMhqkyhWdDeYrgYqYSOJhfz89SNJF34fmVTlsqSxnc7JrxwVWYlS7clkvyXrtJvD4HWGj9ZLnZG2bfgQqVRIh1yadAsbU98hw11I+8rXo7IN7rcX7ofQhJd8VLetbY0QdvEzVmvD69S0/gO+IOSBmDe9iDHt+dPvv3OyctobYPFJjrRTHyOLlvTgFeVgD8EplLb/hHjwq9ldCT0wd4xJAFxc07C7BrM95PcPKWCCDXUD7QZwnSs2UYQoVgAcGszU1vwnFtx0lWw4Er/6Yo+irptffakGz6i76poIaR59do4OByrlMMPYhVNWtszTmnztOvrph0Gi85ulEIC5YkBdBpAMjlQydeYaNobOlcZJh4uxCFdh3lzU1nW9MtcOpX13VFnj2ukTNdZVF4hbZs2sfE5QAdjlaFpgj8FvsXzyOJrcwMNbWPURNKM0EqQ/LIUKxb/N2SHjkUE9Al86yfWgFpYrOrR/Pg6x7ayagFgRM=
